FROM python:3.9-slim

WORKDIR /app/backend/history-service

COPY ./history-service/requirements.txt ./

RUN pip install -r requirements.txt

COPY ./history-service ./

EXPOSE 8001

CMD ["nohup", "uvicorn", "main:app", "--reload", "--port", "8001"]