FROM python:3.11.0-bullseye

WORKDIR  /app/backend/user-service

# Install dependencies:
COPY ./user-service/requirements.txt .
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
RUN . /opt/venv/bin/activate && pip install -r requirements.txt

COPY ./user-service ./

EXPOSE 8000
CMD /opt/venv/bin/python3 -m uvicorn main:app --host 0.0.0.0 --port 8000

