FROM python:3.11.0-bullseye

WORKDIR  /app/backend/code-execution-service

# Install dependencies:
COPY ./code-execution-service/requirements.txt .
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
RUN . /opt/venv/bin/activate && pip install -r requirements.txt

COPY ./code-execution-service ./

EXPOSE 5001
CMD /opt/venv/bin/python3 -m uvicorn main:app --host 0.0.0.0 --port 5001