FROM python:3.9-slim

WORKDIR /app/backend/communication-service

COPY ./communication-service/requirements.txt ./

RUN pip install -r requirements.txt

COPY ./communication-service ./

EXPOSE 8003

CMD ["nohup", "uvicorn", "main:app", "--reload", "--port", "8003"]