FROM node:16

WORKDIR /app/backend/collaboration-service

COPY ./collaboration-service/package.json ./
COPY ./collaboration-service/package-lock.json ./

RUN npm install

COPY ./collaboration-service ./

EXPOSE 8004

CMD ["npm", "run", "dev"]