FROM python:3.9-slim

WORKDIR /app/backend/user-service

COPY ./user-service/requirements.txt ./

RUN pip install -r requirements.txt

COPY ./user-service ./

EXPOSE 8000

CMD ["nohup", "uvicorn", "main:app", "--reload", "--port", "8000"]
