FROM python:3.9-slim

WORKDIR /app/backend/question-service

COPY ./question-service/requirements.txt ./

RUN pip install -r requirements.txt

COPY ./question-service ./

EXPOSE 8005

CMD ["nohup", "uvicorn", "main:app", "--reload", "--port", "8005"]